version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: ./dockers/php/Dockerfile
    volumes:
      - ./source/app:/var/www
    container_name:
      webapp
    networks: 
      - code-network
    ports:
      - "8080:8000"
    command:
    #   php artisan serve
      php artisan serve --host=0.0.0.0 --port=8000
    links:
      - postgres

  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    # volumes:
    #    - "./sourcefiles/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=blog
    ports:
     - "5432:5432"
    networks:
      - code-network
    #       testing_net:
    #           ipv4_address: 172.28.1.2

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   depends_on:
  #     - webapp
  #   volumes:
  #     - ./source/app:/var/www
  #     - ./conf/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"

networks:
    code-network:
        driver: bridge

